//NEST NEW NUEVO PROYECTO
//YARN START:DEV
//CREAR EL DOCKERCOMPOSE.YAML
//.ENV CREAR 2 VARIBALES LA DB Y PASSWORD Y SE LAS PASAMOS AL DOCKER COMPOSE
//DOCKER COMPOSE UP COMANDO CORRER VER QUE EN DOCKER YA ESTA EL CONTENEDOR
//TABLE PLUS ABRIR Y  CREAR NUEVA CONEXION
//POSGRESQL---NOMBRE EL QUE SEA---LOCALHOST---USER POSTGRES- CONTRASEÑA LA DEL .ENV--- CONEXION-- SALVAR
//INSTALACION DE yarn add @nestjs/config
//AGREGAR ConfigModule.forRoot EN APP MODULE
//INSTALAR yarn add @nestjs/typeorm typeorm
//nest g res products
//PRODUCTS ENTITY CREAR TODAS LAS COLUMNAS CON LOS VALORES
//EN MAIN PONER EL USEGLOBAL PIPES
//EN EL PRODUCT.SERVICE HACER EL CONSTRUCTOR
